import mongoose from "mongoose";
import Order from "../models/Order.js";
import OrderItem from "../models/OrderItem.js";
import Product from "../models/Product.js";
import { ErrorResponse } from "../utils/errorResponse.js";
import ghnService from "./ghn.service.js";
import User from "../models/User.js";
import { simulateGHNWebhook } from "../utils/simulateGHNWebhook.js";
import * as orderTrackingService from "./orderTracking.service.js";

/**
 * Create a new order
 */
export const createOrder = async (orderData) => {
  const {
    userId,
    subtotal,
    shippingCost = 0,
    tax = 0,
    discount = 0,
    totalPrice,
    shippingAddress,
    shippingMethod = "standard",
    paymentMethod = "cash_on_delivery",
    discountCode,
    notes,
    items = [],
  } = orderData;

  // Validation
  if (
    !userId ||
    !subtotal ||
    !totalPrice ||
    !shippingAddress ||
    !paymentMethod
  ) {
    throw new ErrorResponse(
      "Missing required fields: userId, subtotal, totalPrice, shippingAddress, paymentMethod",
      400,
    );
  }

  // Validate userId is a valid ObjectId
  if (!mongoose.Types.ObjectId.isValid(userId)) {
    throw new ErrorResponse(
      `Invalid userId format. Must be a valid MongoDB ObjectId. Received: ${userId}`,
      400,
    );
  }

  // Create order - orderNumber will be auto-generated by pre-save hook
  const order = new Order({
    userId,
    subtotal,
    shippingCost,
    tax,
    discount,
    totalPrice,
    shippingAddress,
    shippingMethod,
    paymentMethod,
    discountCode,
    notes,
    status: "pending",
    paymentStatus: "pending",
  });

  await order.save();

  // Create order items if provided
  if (items && items.length > 0) {
    const orderItems = await Promise.all(
      items.map((item) =>
        OrderItem.create({
          orderId: order._id,
          productId: item.productId,
          modelId: item.modelId,
          sku: item.sku,
          quantity: item.quantity,
          price: item.price,
          tierSelections: item.tierSelections || {},
          subtotal: item.subtotal || item.quantity * item.price,
          originalPrice: item.originalPrice,
          isFlashSale: item.isFlashSale || false,
        }),
      ),
    );

    order.items = orderItems.map((item) => item._id);
    await order.save();
  }

  // Populate and return
  const populatedOrder = await Order.findById(order._id).populate("items");

  return populatedOrder;
};

/**
 * Get all orders with pagination and filters
 * Returns orders that contain products from the seller
 */
export const getSellerOrders = async (filters = {}, sellerId) => {
  const { page = 1, limit = 10, status, sortBy = "createdAt" } = filters;
  const skip = (page - 1) * limit;

  if (!sellerId) {
    throw new ErrorResponse("Seller ID is required", 400);
  }

  // Find all products belonging to this seller
  const sellerProducts = await Product.find({ sellerId }).select("_id");
  const sellerProductIds = sellerProducts.map((p) => p._id);

  if (sellerProductIds.length === 0) {
    return {
      total: 0,
      page: Number(page),
      limit: Number(limit),
      pages: 0,
      data: [],
    };
  }

  // Find OrderItems containing seller's products
  const orderItems = await OrderItem.find({
    productId: { $in: sellerProductIds },
  }).select("orderId");
  const orderIds = [
    ...new Set(orderItems.map((item) => item.orderId.toString())),
  ].map((id) => new mongoose.Types.ObjectId(id));

  if (orderIds.length === 0) {
    return {
      total: 0,
      page: Number(page),
      limit: Number(limit),
      pages: 0,
      data: [],
    };
  }

  // Build filter
  const filterQuery = { _id: { $in: orderIds } };
  if (status) {
    filterQuery.status = status;
  }

  // Sort options
  const sortOptions = {
    createdAt: { createdAt: -1 },
    "newest-first": { createdAt: -1 },
    "oldest-first": { createdAt: 1 },
    "total-high": { totalPrice: -1 },
    "total-low": { totalPrice: 1 },
  };

  const orders = await Order.find(filterQuery)
    .populate("userId", "fullName email phone")
    .populate({
      path: "items",
      populate: {
        path: "productId",
        select: "name images originalPrice models tiers",
      },
    })
    .sort(sortOptions[sortBy] || { createdAt: -1 })
    .skip(skip)
    .limit(Number(limit));

  const total = await Order.countDocuments(filterQuery);

  // Enrich items with selected model only
  const enrichedOrders = orders.map((order) => ({
    ...order.toObject(),
    items: order.items.map((item) => {
      const selectedModel = item.productId.models?.find(
        (m) => m._id.toString() === item.modelId.toString(),
      );
      const tierDetails = enrichTierDetails(
        item,
        selectedModel,
        item.productId.tiers,
      );

      return {
        ...item.toObject(),
        tierDetails,
        productId: {
          ...item.productId.toObject(),
          selectedModel,
          models: undefined,
          tiers: undefined,
        },
      };
    }),
  }));

  return {
    total,
    page: Number(page),
    limit: Number(limit),
    pages: Math.ceil(total / limit),
    data: enrichedOrders,
  };
};

/**
 * Get orders filtered by specific status
 */
export const getOrdersByStatus = async (status, pagination = {}, sellerId) => {
  const { page = 1, limit = 10 } = pagination;
  const skip = (page - 1) * limit;

  if (!sellerId) {
    throw new ErrorResponse("Seller ID is required", 400);
  }

  const validStatuses = [
    "pending",
    "confirmed",
    "packing",
    "shipping",
    "delivered",
    "delivered_pending_confirmation",
    "completed",
    "cancelled",
    "refunded",
    "refund_pending",
    "under_investigation",
    // Backward-compatible statuses
    "processing",
    "shipped",
  ];

  if (!validStatuses.includes(status)) {
    throw new ErrorResponse(
      `Invalid status. Valid statuses: ${validStatuses.join(", ")}`,
      400,
    );
  }

  const sellerProducts = await Product.find({ sellerId }).select("_id");
  const sellerProductIds = sellerProducts.map((p) => p._id);

  if (sellerProductIds.length === 0) {
    return {
      total: 0,
      page: Number(page),
      limit: Number(limit),
      pages: 0,
      statusCounts: {},
      data: [],
    };
  }

  const orderItems = await OrderItem.find({
    productId: { $in: sellerProductIds },
  }).select("orderId");
  const orderIds = [
    ...new Set(orderItems.map((item) => item.orderId.toString())),
  ].map((id) => new mongoose.Types.ObjectId(id));

  if (orderIds.length === 0) {
    return {
      total: 0,
      page: Number(page),
      limit: Number(limit),
      pages: 0,
      statusCounts: {},
      data: [],
    };
  }

  const filter = { _id: { $in: orderIds }, status };

  const orders = await Order.find(filter)
    .populate("userId", "fullName email phone")
    .populate({
      path: "items",
      populate: {
        path: "productId",
        select: "name images originalPrice models tiers",
      },
    })
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(Number(limit));

  const total = await Order.countDocuments(filter);

  const statusCounts = await Order.aggregate([
    { $match: { _id: { $in: orderIds } } },
    { $group: { _id: "$status", count: { $sum: 1 } } },
  ]);

  // Enrich items with selected model only
  const enrichedOrders = orders.map((order) => ({
    ...order.toObject(),
    items: order.items.map((item) => {
      const selectedModel = item.productId.models?.find(
        (m) => m._id.toString() === item.modelId.toString(),
      );
      const tierDetails = enrichTierDetails(
        item,
        selectedModel,
        item.productId.tiers,
      );

      return {
        ...item.toObject(),
        tierDetails,
        productId: {
          ...item.productId.toObject(),
          selectedModel,
          models: undefined,
          tiers: undefined,
        },
      };
    }),
  }));

  return {
    total,
    page: Number(page),
    limit: Number(limit),
    pages: Math.ceil(total / limit),
    statusCounts: statusCounts.reduce((acc, item) => {
      acc[item._id] = item.count;
      return acc;
    }, {}),
    data: enrichedOrders,
  };
};

/**
 * Get order status history (audit log)
 */
export const getOrderStatusHistory = async (orderId) => {
  const order = await Order.findById(orderId)
    .select("orderNumber status statusHistory")
    .populate("statusHistory.changedBy", "fullName email role");

  if (!order) {
    throw new ErrorResponse("Order not found", 404);
  }

  return {
    orderNumber: order.orderNumber,
    currentStatus: order.status,
    history: order.statusHistory.sort(
      (a, b) => new Date(b.changedAt) - new Date(a.changedAt),
    ),
  };
};

/**
 * Get order detail by ID
 */
export const getOrderDetail = async (orderId) => {
  const order = await Order.findById(orderId)
    .populate("userId")
    .populate({
      path: "items",
      populate: {
        path: "productId",
        select: "name images originalPrice models tiers",
      },
    })
    .populate("shipperId", "fullName phone");

  if (!order) {
    throw new ErrorResponse("Order not found", 404);
  }

  // Enrich items with selected model only
  const enrichedOrder = {
    ...order.toObject(),
    items: order.items.map((item) => {
      const selectedModel = item.productId.models?.find(
        (m) => m._id.toString() === item.modelId.toString(),
      );
      const tierDetails = enrichTierDetails(
        item,
        selectedModel,
        item.productId.tiers,
      );

      return {
        ...item.toObject(),
        tierDetails,
        productId: {
          ...item.productId.toObject(),
          selectedModel,
          models: undefined,
          tiers: undefined,
        },
      };
    }),
  };

  return enrichedOrder;
};

/**
 * Update order status with validation
 */
export const updateOrderStatus = async (orderId, updateData, userData) => {
  const { newStatus, trackingNumber, estimatedDelivery, notes, reason } =
    updateData;
  const { userId, userRole } = userData;

  const order = await Order.findById(orderId);

  if (!order) {
    throw new ErrorResponse("Order not found", 404);
  }

  // Validate status transition
  // Canonical workflow: pending -> confirmed -> packed -> shipped -> delivered -> completed
  // Keep backward-compatible legacy states (processing, packing, shipping, shipped)
  const validTransitions = {
    pending: ["confirmed", "processing", "cancelled"],
    processing: ["confirmed", "packing", "cancelled"],
    confirmed: ["packed", "packing", "shipping", "cancelled"],
    packing: ["packed", "shipping", "cancelled"],
    packed: ["shipping", "cancelled"],
    shipping: ["shipped", "delivered"],
    shipped: ["delivered", "refund_pending"],
    delivered: ["delivered_pending_confirmation", "completed"],
    delivered_pending_confirmation: ["completed", "refund_pending"],
    completed: [],
    cancelled: [],
    refund_pending: ["refunded", "under_investigation"],
    refunded: [],
    under_investigation: ["completed", "refunded"],
  };

  if (!validTransitions[order.status]?.includes(newStatus)) {
    throw new ErrorResponse(
      `Cannot transition from '${order.status}' to '${newStatus}'`,
      400,
    );
  }

  // Store old status for history
  const oldStatus = order.status;

  // Update status
  order.status = newStatus;

  // Update tracking and estimated delivery if provided
  if (trackingNumber) order.trackingNumber = trackingNumber;
  if (estimatedDelivery) order.estimatedDelivery = estimatedDelivery;
  if (notes) order.notes = notes;

  // Add to status history
  order.statusHistory.push({
    status: newStatus,
    changedBy: userId,
    changedByRole: userRole,
    changedAt: new Date(),
    reason: reason || `Changed from ${oldStatus} to ${newStatus}`,
    notes: notes || undefined,
  });

  // Auto-create GHN shipping order when status changes to 'processing' or 'confirmed'
  // (some flows use 'processing' historically; new canonical flow may use 'confirmed')
  if (
    (newStatus === "processing" || newStatus === "confirmed") &&
    !order.ghnOrderCode
  ) {
    console.log("[Order Service] Creating GHN shipping order...");

    try {
      // Populate order items and user info
      await order.populate("items");
      await order.populate("userId", "fullName phone email");

      // Parse shipping address (basic implementation)
      // In production, you should have structured address with district/ward IDs
      const customerInfo = {
        to_name: order.userId.fullName || "Customer",
        to_phone: order.userId.phone || "0901234567",
        to_address: order.shippingAddress,
        to_district_id: 1542, // Default: Quận 10, TP.HCM (should get from address data)
        to_ward_code: "21211", // Default: Phường 14 (should get from address data)
      };

      // Build GHN items payload from order items
      const ghnItems = (order.items || []).map((it) => ({
        name: it.productId?.name || it.sku || `Item-${it._id}`,
        quantity: Number(it.quantity) || 1,
        price: Math.round(it.price || 0),
      }));

      // Compute total weight (fallback to 500g if unknown)
      const totalWeight = (order.items || []).reduce((sum, it) => {
        const itemWeight =
          Number(it.weight) || Number(it.productId?.weight) || 0;
        return sum + itemWeight * (Number(it.quantity) || 1);
      }, 0);

      const ghnOrderData = {
        client_order_code: order.orderNumber,
        to_name: customerInfo.to_name,
        to_phone: customerInfo.to_phone,
        to_address: customerInfo.to_address,
        to_district_id: customerInfo.to_district_id,
        to_ward_code: customerInfo.to_ward_code,
        cod_amount:
          order.paymentMethod === "cash_on_delivery"
            ? Math.round(order.totalPrice)
            : 0,
        weight: totalWeight || 500,
        items: ghnItems,
        note: order.notes || `Đơn hàng ${order.orderNumber}`,
        insurance_value: Math.round(order.totalPrice),
      };

      const ghnResponse = await ghnService.createShippingOrder(ghnOrderData);

      if (ghnResponse.success) {
        console.log("[Order Service] GHN order created:", ghnResponse.data);

        // Update order with GHN information
        order.ghnOrderCode = ghnResponse.data.order_code;
        order.ghnSortingCode = ghnResponse.data.sort_code;
        order.trackingNumber = ghnResponse.data.order_code; // Use GHN order code as tracking number
        order.ghnExpectedDeliveryTime = ghnResponse.data.expected_delivery_time
          ? new Date(ghnResponse.data.expected_delivery_time)
          : null;
        order.ghnShippingFee = ghnResponse.data.total_fee || 0;
        order.ghnOrderInfo = ghnResponse.data;
        order.ghnStatus = "ready_to_pick";
        // Add a system status history entry about GHN creation
        order.statusHistory.push({
          status: newStatus,
          changedBy: userId || null,
          changedByRole: "system",
          changedAt: new Date(),
          reason: "Đơn hàng đã được tạo trên GHN, chờ shipper đến lấy",
        });

        // Update estimated delivery if available
        if (ghnResponse.data.expected_delivery_time) {
          order.estimatedDelivery = new Date(
            ghnResponse.data.expected_delivery_time,
          );
        }

        console.log("[Order Service] ✅ GHN order created successfully");
        console.log("[Order Service] Tracking number:", order.trackingNumber);

        // 🎬 Demo: tự động giả lập cập nhật trạng thái giao hàng
        // Step 1 (+10s): GHN "picking"   → system "shipped"
        // Step 2 (+20s): GHN "delivered" → system "completed"
        simulateGHNWebhook(order.ghnOrderCode, order.orderNumber);
      } else {
        console.error(
          "[Order Service] ❌ Failed to create GHN order:",
          ghnResponse.error,
        );
        // Don't throw error, just log it - order status update should still proceed
        order.statusHistory.push({
          status: newStatus,
          changedBy: userId,
          changedByRole: "system",
          changedAt: new Date(),
          reason: "GHN order creation failed",
          notes: `Error: ${ghnResponse.error?.message || "Unknown error"}`,
        });
      }
    } catch (ghnError) {
      console.error(
        "[Order Service] Exception while creating GHN order:",
        ghnError,
      );
      // Don't throw - allow status update to proceed
    }
  }

  await order.save();

  const updatedOrder = await Order.findById(orderId)
    .populate("userId", "fullName email phone")
    .populate({
      path: "items",
      populate: {
        path: "productId",
        select: "name images originalPrice models tiers",
      },
    })
    .populate("statusHistory.changedBy", "fullName email role");

  // Enrich items with selected model only
  const enrichedOrder = {
    ...updatedOrder.toObject(),
    items: updatedOrder.items.map((item) => {
      const selectedModel = item.productId.models?.find(
        (m) => m._id.toString() === item.modelId.toString(),
      );
      const tierDetails = enrichTierDetails(
        item,
        selectedModel,
        item.productId.tiers,
      );

      return {
        ...item.toObject(),
        tierDetails,
        productId: {
          ...item.productId.toObject(),
          selectedModel,
          models: undefined,
          tiers: undefined,
        },
      };
    }),
  };

  return enrichedOrder;
};

/**
 * Cancel order with reason
 */
export const cancelOrder = async (orderId, cancellationReason) => {
  const order = await Order.findById(orderId);

  if (!order) {
    throw new ErrorResponse("Order not found", 404);
  }

  // Can only cancel orders that haven't reached delivery; include backward-compatible and canonical statuses
  if (
    ![
      "pending",
      "processing",
      "confirmed",
      "packing",
      "packed",
      "shipping",
    ].includes(order.status)
  ) {
    throw new ErrorResponse(
      `Cannot cancel order with status '${order.status}'`,
      400,
    );
  }

  // FIX BUG 13: Cancel delivery timer if order was in shipping status
  if (order.status === "shipping") {
    const cancelled = orderTrackingService.cancelDeliveryTimer(orderId);
    if (cancelled) {
      console.log(
        `[CancelOrder] Delivery timer cancelled for order ${orderId}`,
      );
    }
  }

  order.status = "cancelled";
  order.cancelledAt = new Date();
  order.cancellationReason = cancellationReason || "Cancelled";

  await order.save();

  const updatedOrder = await Order.findById(orderId)
    .populate("userId", "fullName email phone")
    .populate({
      path: "items",
      populate: {
        path: "productId",
        select: "name images originalPrice models tiers",
      },
    });

  // Enrich items with selected model only
  const enrichedOrder = {
    ...updatedOrder.toObject(),
    items: updatedOrder.items.map((item) => {
      const selectedModel = item.productId.models?.find(
        (m) => m._id.toString() === item.modelId.toString(),
      );
      const tierDetails = enrichTierDetails(
        item,
        selectedModel,
        item.productId.tiers,
      );

      return {
        ...item.toObject(),
        tierDetails,
        productId: {
          ...item.productId.toObject(),
          selectedModel,
          models: undefined,
          tiers: undefined,
        },
      };
    }),
  };

  return enrichedOrder;
};

/**
 * Generate delivery note (HTML format)
 */
export const generateDeliveryNote = async (orderId) => {
  const order = await Order.findById(orderId)
    .populate("userId")
    .populate("items");

  if (!order) {
    throw new ErrorResponse("Order not found", 404);
  }

  const html = generateDeliveryNoteHTML(order);

  return {
    html,
    orderNumber: order.orderNumber,
  };
};

/**
 * Helper function to generate delivery note HTML
 */
function generateDeliveryNoteHTML(order) {
  const itemsHTML = order.items
    .map((item) => {
      const tierSelectionsStr =
        Array.from(item.tierSelections || [])
          .map(([tier, selection]) => `${tier}: ${selection}`)
          .join(", ") || "N/A";

      return `
    <tr>
      <td style="padding: 8px; border: 1px solid #ddd;">SKU: ${item.sku}, ${tierSelectionsStr}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">${item.quantity}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: right;">₫${item.price.toLocaleString()}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: right;">₫${item.subtotal.toLocaleString()}</td>
    </tr>
  `;
    })
    .join("");

  return `
    <!DOCTYPE html>
    <html lang="vi">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Phiếu Giao Hàng - ${order.orderNumber}</title>
      <style>
        body { font-family: 'Arial', sans-serif; margin: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; color: #333; }
        .header p { margin: 5px 0; color: #666; }
        .info-section { margin-bottom: 20px; }
        .info-section h3 { background-color: #f5f5f5; padding: 10px; margin: 0 0 10px 0; }
        .info-row { display: flex; margin-bottom: 8px; }
        .info-label { font-weight: bold; width: 150px; }
        .info-value { flex: 1; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background-color: #f5f5f5; padding: 10px; border: 1px solid #ddd; text-align: left; }
        .total-row { font-weight: bold; background-color: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📦 PHIẾU GIAO HÀNG</h1>
        <p>Order #${order.orderNumber}</p>
        <p>Ngày tạo: ${new Date(order.createdAt).toLocaleDateString("vi-VN")}</p>
      </div>

      <div class="info-section">
        <h3>Thông Tin Người Nhận</h3>
        <div class="info-row">
          <span class="info-label">Họ tên:</span>
          <span class="info-value">${order.userId?.fullName || "N/A"}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Điện thoại:</span>
          <span class="info-value">${order.userId?.phone || "N/A"}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Địa chỉ:</span>
          <span class="info-value">${order.shippingAddress}</span>
        </div>
      </div>

      <div class="info-section">
        <h3>Chi Tiết Đơn Hàng</h3>
        <table>
          <thead>
            <tr>
              <th>Sản Phẩm (SKU, Chi tiết)</th>
              <th style="text-align: center;">Số Lượng</th>
              <th style="text-align: right;">Giá</th>
              <th style="text-align: right;">Thành Tiền</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHTML}
            <tr class="total-row">
              <td colspan="3" style="text-align: right; padding: 10px; border: 1px solid #ddd;">Tổng cộng:</td>
              <td style="text-align: right; padding: 10px; border: 1px solid #ddd;">₫${order.totalPrice.toLocaleString()}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="info-section">
        <h3>Ghi Chú</h3>
        <div class="info-row">
          <span class="info-value">${order.notes || "Không có ghi chú"}</span>
        </div>
      </div>

      <div class="footer">
        <p>Phiếu này được in từ hệ thống GZMart - ${new Date().toLocaleDateString("vi-VN")}</p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Helper function to enrich tier details from tierIndex
 * Maps tierIndex to tier names and values
 */
function enrichTierDetails(item, selectedModel, tiers) {
  if (
    !selectedModel ||
    !tiers ||
    tiers.length === 0 ||
    !selectedModel.tierIndex
  ) {
    return item.tierSelections || {};
  }

  const tierDetails = {};
  selectedModel.tierIndex.forEach((index, tierPosition) => {
    if (
      tiers[tierPosition] &&
      tiers[tierPosition].options &&
      tiers[tierPosition].options[index]
    ) {
      tierDetails[tiers[tierPosition].name] =
        tiers[tierPosition].options[index];
    }
  });

  return tierDetails;
}
