import mongoose from 'mongoose';
import Order from '../models/Order.js';
import OrderItem from '../models/OrderItem.js';

/**
 * Create a new order
 * Body: { userId, subtotal, shippingCost, totalPrice, shippingAddress, paymentMethod, items[], ... }
 */
export const createOrder = async (req, res, next) => {
  try {
    const {
      userId,
      subtotal,
      shippingCost = 0,
      tax = 0,
      discount = 0,
      totalPrice,
      shippingAddress,
      shippingMethod = 'standard',
      paymentMethod = 'cash_on_delivery',
      discountCode,
      notes,
      items = [],
    } = req.body;

    // Validation
    if (!userId || !subtotal || !totalPrice || !shippingAddress || !paymentMethod) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields: userId, subtotal, totalPrice, shippingAddress, paymentMethod',
      });
    }

    // Validate userId is a valid ObjectId
    if (!mongoose.Types.ObjectId.isValid(userId)) {
      return res.status(400).json({
        success: false,
        message: `Invalid userId format. Must be a valid MongoDB ObjectId. Received: ${userId}`,
        hint: 'Get a valid user ID from MongoDB or create a test user first',
      });
    }

    // Create order - orderNumber will be auto-generated by pre-save hook
    const order = new Order({
      userId,
      subtotal,
      shippingCost,
      tax,
      discount,
      totalPrice,
      shippingAddress,
      shippingMethod,
      paymentMethod,
      discountCode,
      notes,
      status: 'pending',
      paymentStatus: 'pending',
    });

    await order.save();

    // Create order items if provided
    if (items && items.length > 0) {
      const orderItems = await Promise.all(
        items.map((item) =>
          OrderItem.create({
            orderId: order._id,
            productId: item.productId,
            quantity: item.quantity,
            price: item.price,
            size: item.size || 'M',
            color: item.color || 'Default',
            subtotal: item.subtotal || item.quantity * item.price,
            originalPrice: item.originalPrice,
            isFlashSale: item.isFlashSale || false,
          })
        )
      );

      order.items = orderItems.map((item) => item._id);
      await order.save();
    }

    // Populate and return
    const populatedOrder = await Order.findById(order._id).populate('items');

    res.status(201).json({
      success: true,
      message: 'Order created successfully',
      data: populatedOrder,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get all orders for a seller with pagination and filters
 * Query params: page, limit, status, sortBy
 */
export const getSellerOrders = async (req, res, next) => {
  try {
    const { page = 1, limit = 10, status, sortBy = 'createdAt' } = req.query;
    const skip = (page - 1) * limit;

    // Build filter
    const filter = {};
    if (status) {
      filter.status = status;
    }

    // Sort options
    const sortOptions = {
      createdAt: { createdAt: -1 },
      'newest-first': { createdAt: -1 },
      'oldest-first': { createdAt: 1 },
      'total-high': { totalPrice: -1 },
      'total-low': { totalPrice: 1 },
    };

    const orders = await Order.find(filter)
      .populate('userId', 'fullName email phone')
      .populate('items')
      .sort(sortOptions[sortBy] || { createdAt: -1 })
      .skip(skip)
      .limit(Number(limit))
      .lean();

    const total = await Order.countDocuments(filter);

    res.status(200).json({
      success: true,
      total,
      page: Number(page),
      limit: Number(limit),
      pages: Math.ceil(total / limit),
      data: orders,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get orders filtered by specific status
 */
export const getOrdersByStatus = async (req, res, next) => {
  try {
    const { status } = req.params;
    const { page = 1, limit = 10 } = req.query;
    const skip = (page - 1) * limit;

    const validStatuses = [
      'pending',
      'processing',
      'shipped',
      'delivered',
      'delivered_pending_confirmation',
      'completed',
      'cancelled',
      'refunded',
      'refund_pending',
      'under_investigation',
    ];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        message: `Invalid status. Valid statuses: ${validStatuses.join(', ')}`,
      });
    }

    const filter = { status };

    const orders = await Order.find(filter)
      .populate('userId', 'fullName email phone')
      .populate('items')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(Number(limit))
      .lean();

    const total = await Order.countDocuments(filter);

    const statusCounts = await Order.aggregate([
      { $group: { _id: '$status', count: { $sum: 1 } } },
    ]);

    res.status(200).json({
      success: true,
      total,
      page: Number(page),
      limit: Number(limit),
      pages: Math.ceil(total / limit),
      statusCounts: statusCounts.reduce((acc, item) => {
        acc[item._id] = item.count;
        return acc;
      }, {}),
      data: orders,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get order detail by ID
 */
export const getOrderDetail = async (req, res, next) => {
  try {
    const { orderId } = req.params;

    const order = await Order.findById(orderId)
      .populate('userId')
      .populate('items')
      .populate('shipperId', 'fullName phone');

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found',
      });
    }

    res.status(200).json({
      success: true,
      data: order,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Update order status with validation
 * Body: { newStatus, trackingNumber?, estimatedDelivery?, notes? }
 */
export const updateOrderStatus = async (req, res, next) => {
  try {
    const { orderId } = req.params;
    const { newStatus, trackingNumber, estimatedDelivery, notes } = req.body;

    const order = await Order.findById(orderId);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found',
      });
    }

    // Validate status transition
    const validTransitions = {
      pending: ['processing', 'cancelled'],
      processing: ['shipped', 'cancelled'],
      shipped: ['delivered', 'refund_pending'],
      delivered: ['delivered_pending_confirmation'],
      delivered_pending_confirmation: ['completed', 'refund_pending'],
      completed: [],
      cancelled: [],
      refund_pending: ['refunded', 'under_investigation'],
      refunded: [],
      under_investigation: ['completed', 'refunded'],
    };

    if (!validTransitions[order.status]?.includes(newStatus)) {
      return res.status(400).json({
        success: false,
        message: `Cannot transition from '${order.status}' to '${newStatus}'`,
        validTransitions: validTransitions[order.status] || [],
      });
    }

    // Update status
    order.status = newStatus;

    // Update tracking and estimated delivery if provided
    if (trackingNumber) order.trackingNumber = trackingNumber;
    if (estimatedDelivery) order.estimatedDelivery = estimatedDelivery;
    if (notes) order.notes = notes;

    await order.save();

    const updatedOrder = await Order.findById(orderId)
      .populate('userId', 'fullName email phone')
      .populate('items');

    res.status(200).json({
      success: true,
      message: `Order status updated to '${newStatus}'`,
      data: updatedOrder,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Cancel order with reason
 * Body: { cancellationReason }
 */
export const cancelOrder = async (req, res, next) => {
  try {
    const { orderId } = req.params;
    const { cancellationReason } = req.body;

    const order = await Order.findById(orderId);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found',
      });
    }

    // Can only cancel pending or processing orders
    if (!['pending', 'processing'].includes(order.status)) {
      return res.status(400).json({
        success: false,
        message: `Cannot cancel order with status '${order.status}'`,
      });
    }

    order.status = 'cancelled';
    order.cancelledAt = new Date();
    order.cancellationReason = cancellationReason || 'Cancelled';

    await order.save();

    const updatedOrder = await Order.findById(orderId)
      .populate('userId', 'fullName email phone')
      .populate('items');

    res.status(200).json({
      success: true,
      message: 'Order cancelled successfully',
      data: updatedOrder,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Generate delivery note (HTML format - can be converted to PDF)
 */
export const generateDeliveryNote = async (req, res, next) => {
  try {
    const { orderId } = req.params;

    const order = await Order.findById(orderId)
      .populate('userId')
      .populate('items');

    if (!order) {
      return res.status(404).json({
        success: false,
        message: 'Order not found',
      });
    }

    // Generate HTML
    const html = generateDeliveryNoteHTML(order);

    res.status(200).json({
      success: true,
      html,
      orderNumber: order.orderNumber,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Helper function to generate delivery note HTML
 */
function generateDeliveryNoteHTML(order) {
  const itemsHTML = order.items
    .map(
      (item) => `
    <tr>
      <td style="padding: 8px; border: 1px solid #ddd;">Size: ${item.size}, Color: ${item.color}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">${item.quantity}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: right;">₫${item.price.toLocaleString()}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: right;">₫${item.subtotal.toLocaleString()}</td>
    </tr>
  `
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html lang="vi">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Phiếu Giao Hàng - ${order.orderNumber}</title>
      <style>
        body { font-family: 'Arial', sans-serif; margin: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; color: #333; }
        .header p { margin: 5px 0; color: #666; }
        .info-section { margin-bottom: 20px; }
        .info-section h3 { background-color: #f5f5f5; padding: 10px; margin: 0 0 10px 0; }
        .info-row { display: flex; margin-bottom: 8px; }
        .info-label { font-weight: bold; width: 150px; }
        .info-value { flex: 1; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background-color: #f5f5f5; padding: 10px; border: 1px solid #ddd; text-align: left; }
        .total-row { font-weight: bold; background-color: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📦 PHIẾU GIAO HÀNG</h1>
        <p>Order #${order.orderNumber}</p>
        <p>Ngày tạo: ${new Date(order.createdAt).toLocaleDateString('vi-VN')}</p>
      </div>

      <div class="info-section">
        <h3>Thông Tin Người Nhận</h3>
        <div class="info-row">
          <span class="info-label">Họ tên:</span>
          <span class="info-value">${order.userId?.fullName || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Điện thoại:</span>
          <span class="info-value">${order.userId?.phone || 'N/A'}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Địa chỉ:</span>
          <span class="info-value">${order.shippingAddress}</span>
        </div>
      </div>

      <div class="info-section">
        <h3>Chi Tiết Đơn Hàng</h3>
        <table>
          <thead>
            <tr>
              <th>Sản Phẩm (Size, Color)</th>
              <th style="text-align: center;">Số Lượng</th>
              <th style="text-align: right;">Giá</th>
              <th style="text-align: right;">Thành Tiền</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHTML}
            <tr class="total-row">
              <td colspan="3" style="text-align: right; padding: 10px; border: 1px solid #ddd;">Tổng cộng:</td>
              <td style="text-align: right; padding: 10px; border: 1px solid #ddd;">₫${order.totalPrice.toLocaleString()}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="info-section">
        <h3>Ghi Chú</h3>
        <div class="info-row">
          <span class="info-value">${order.notes || 'Không có ghi chú'}</span>
        </div>
      </div>

      <div class="footer">
        <p>Phiếu này được in từ hệ thống GZMart - ${new Date().toLocaleDateString('vi-VN')}</p>
      </div>
    </body>
    </html>
  `;
}
